name: Release Workflow

on:
  schedule:
    - cron:  "0 2 * * *" # Run at 2:00 AM every day
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  extract-version:
    runs-on: ubuntu-latest
    name: Extract Version
    outputs:
      versions_differ: ${{ steps.compare_versions.outputs.versions_differ }}
      lbm_version: ${{ steps.get_lbm_version.outputs.lbm_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get LiveboxMonitor current version
        id: get_lbm_version
        run: |
          LBM_VERSION=v$(curl -s https://api.github.com/repos/p-dor/LiveboxMonitor/releases/latest | jq -r '.tag_name')
          echo "Current LiveboxMonitor version is $LBM_VERSION"
          echo "lbm_version=$LBM_VERSION" >> $GITHUB_OUTPUT
      - name: Get latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag is $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
      - name: Compare versions
        id: compare_versions
        run: |
          echo "Comparing LiveboxMonitor version ${{ steps.get_lbm_version.outputs.lbm_version }} with latest tag ${{ steps.get_latest_tag.outputs.latest_tag }}"
          if [ "${{ steps.get_lbm_version.outputs.lbm_version }}" != "${{ steps.get_latest_tag.outputs.latest_tag }}" ]; then
            echo "versions_differ=true" >> $GITHUB_OUTPUT
          else
            echo "versions_differ=false" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-latest
    if: needs.extract-version.outputs.versions_differ == 'true'
    needs: extract-version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build
        uses: ./.github/actions/build
        with:
          version: ${{ needs.extract-version.outputs.lbm_version }}

  test:
    runs-on: ubuntu-latest
    if: needs.extract-version.outputs.versions_differ == 'true'
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test
        uses: ./.github/actions/test
        with:
          version: ${{ needs.extract-version.outputs.lbm_version }}
